export {default as About} from "./About"
export {default as WorkExperience} from "./WorkExperience"
export {default as Qualification} from "./Qualification"
export {default as Projects} from "./Projects"
export { default as Footer } from "./Footer"