import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/components";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div id="circle"></div>
        <main className=" w-full lg:w-[1000px] mx-auto">
          <Navbar className="w-full sm:w-[330px] lg:fixed top-0 bottom-0  py-[70px] lg:py-[100px] px-[25px] sm:px-[20px]" />
          <div className=" lg:pl-[430px]   py-[40px] lg:py-[100px]">
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
